"""empty message

Revision ID: c149847e6f89
Revises: 59f2aa222cb0
Create Date: 2017-05-28 21:52:54.290642

"""

# revision identifiers, used by Alembic.
revision = 'c149847e6f89'
down_revision = '59f2aa222cb0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
