"""empty message

Revision ID: ed67b174eab2
Revises: c149847e6f89
Create Date: 2017-05-28 21:55:16.274157

"""

# revision identifiers, used by Alembic.
revision = 'ed67b174eab2'
down_revision = 'c149847e6f89'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
