"""empty message

Revision ID: 3bfe00ddb422
Revises: ed67b174eab2
Create Date: 2017-05-31 12:22:11.602211

"""

# revision identifiers, used by Alembic.
revision = '3bfe00ddb422'
down_revision = 'ed67b174eab2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
